# EmbedBinary.cmake - convert a binary file's bytes into a generated C++
# source defining a byte array + size symbol.
#
# Invocation (from add_custom_command):
#   ${CMAKE_COMMAND}
#     -DINPUT=<path-to-binary>
#     -DOUTPUT=<path-to-output.cpp>
#     -DSYMBOL=<C-identifier-stem>
#     -P EmbedBinary.cmake
#
# Output file defines:
#   extern "C" const unsigned char ${SYMBOL}_data[<N>];
#   extern "C" const unsigned long ${SYMBOL}_size;
#
# We deliberately avoid an `xxd` tool dependency — pure CMake works on
# every host the rest of the project supports.

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
  message(FATAL_ERROR
    "EmbedBinary.cmake requires -DINPUT, -DOUTPUT, and -DSYMBOL")
endif()

if(NOT EXISTS "${INPUT}")
  message(FATAL_ERROR "EmbedBinary.cmake: input not found: ${INPUT}")
endif()

file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hexlen)
math(EXPR _bytes "${_hexlen} / 2")

set(_body "")
set(_i 0)
set(_col 0)
while(_i LESS ${_hexlen})
  string(SUBSTRING "${_hex}" ${_i} 2 _b)
  string(APPEND _body "0x${_b},")
  math(EXPR _i "${_i} + 2")
  math(EXPR _col "${_col} + 1")
  if(_col EQUAL 16)
    string(APPEND _body "\n")
    set(_col 0)
  endif()
endwhile()

file(WRITE "${OUTPUT}"
"// AUTO-GENERATED by EmbedBinary.cmake — do not edit by hand.\n"
"// Source: ${INPUT}\n"
"// Symbol: ${SYMBOL}\n"
"\n"
"extern \"C\" const unsigned char ${SYMBOL}_data[] = {\n${_body}\n};\n"
"extern \"C\" const unsigned long ${SYMBOL}_size = sizeof(${SYMBOL}_data);\n")
