#!/usr/bin/env python3
"""Generate a `_const_in` sibling recipe from an existing
compare_correctness Triton recipe.

A `_const_in` sibling replaces the base recipe's random inputs with
a near-constant value across every element.  For a deterministic
kernel function (reduction, elementwise, etc.) the native output
becomes analytically predictable, and any salmon deviation carries
VALUE-INDEPENDENT structural information about which specific lifter
path misbehaves.

Why this matters
----------------

The reference case is the V_FMA_MIX_F32_BF16 inline-constant bug
landed in commit 0d002aecf2.  Two days of false leads (DPP rewrite,
EXEC-mask tracking, strict.wwm, d16_hi store) chased a noisy random-
input signal that never pinned the bug.  The const-input probe
produced an immediate, actionable signature: salmon wrote `1.0` when
native wrote `32.0` for a 32-element bf16 sum of all-ones inputs.
From there the lifted-IR audit took 5 minutes — every
`@llvm.fma.f32` had `float 0.000000e+00` as its multiplier.

See `hotswap/docs/learnings.md` entries dated 2026-04-22 for the
full methodology and what the deviation patterns indicate.

Usage
-----

From anywhere (script resolves paths from its arguments):

    python3 \\
      transpiler/tools/const_in_probe/mk_const_in_probe.py \\
      transpiler/tools/compare_correctness/kernels/triton/<recipe>.py \\
      [--const 1.0]

Writes `<recipe>_const_in.py` next to the base recipe with every
input range tightened to `[const, const + epsilon]`.  `const`
defaults to 1.0 (easy analytical prediction for sums / scales).
Any recipe whose `"comparator"` is `{"kind": "abs", "tol": 0.0}`
and whose kernel body is deterministic in the input value will
graduate to `match` on a correctly-lifted salmon; divergence is a
signal worth triaging.

Integration
-----------

* Run manually when adding a new direct-invocation recipe, so the
  probe sibling lands with the base recipe in the same commit.
* Add to CI as a pre-merge gate: for every recipe whose name
  matches a regex (e.g. kernels using `tl.sum` / `tl.max` /
  `tl.cumsum`), require a `_const_in` sibling and run it alongside
  the base.  Failing `_const_in` without a documented reason blocks
  merge.

Limitations (explicit, not deferred-without-documentation)
----------------------------------------------------------

* Only produces sensible analytical predictions for kernels whose
  output is a closed-form function of the scalar input (sums,
  elementwise ops, broadcast / reshape).  Softmax, sort, top-k,
  argmin/argmax, and recurrences need a per-kernel predicted
  output; this script does NOT synthesise those.  Use the probe
  on a narrower sub-shape (bisect the kernel to expose just the
  deterministic stage) — see `topk_forward_bisect_*` for the
  pattern.
* Does not modify the `comparator` tolerance — if the base recipe
  uses `tol: 0.0` and the kernel has non-associative fp ops over
  many elements, the const-input variant may still report drift.
  For bf16 / fp16 outputs, manual tolerance tuning on the sibling
  is expected.
* Assumes flat recipe layout under `kernels/triton/` and exactly
  one recipe per `.py` (both empirically true on the current
  corpus; both checked in `_validate_base_shape`).  Subdirectory
  recipes and multi-recipe files fail loudly at generation time
  with actionable diagnostics rather than producing a silently
  wrong sibling.
* Constant-range epsilon is hard-coded to `1e-3` above the const.
  At bf16 ULP-8 precision around magnitude 1.0, this epsilon is
  ~128x below the ULP, so every input quantises to the same bf16
  value; for fp16 at magnitude 1.0 the same holds (ULP ≈ 2e-4).
  If you need a genuinely sub-ULP epsilon for fp32 / fp64 bases,
  edit `_clone_const_in` — the single-constant-across-inputs
  invariant is what the methodology depends on, not the specific
  epsilon.
"""

from __future__ import annotations

import argparse
import ast
import os
import sys
import textwrap
from pathlib import Path


TEMPLATE = '''\
"""Auto-generated `_const_in` probe for `{base_name}`.

See `hotswap/docs/learnings.md` 2026-04-22 entries for why this
family of probes exists and what deviation patterns mean.

Generated by `transpiler/tools/const_in_probe/mk_const_in_probe.py`.
Regenerate via (from the hotswap/ directory):

    python3 \\
      transpiler/tools/const_in_probe/mk_const_in_probe.py \\
      transpiler/tools/compare_correctness/kernels/triton/{base_path} \\
      --const {const}
"""

# Import the kernel function + recipe dict directly from the base.
# Every compare_correctness Triton recipe .py exports `RECIPES`
# (list of dicts); we clone the first recipe and tighten its input
# ranges to the chosen const.
from {base_module} import RECIPES as _BASE_RECIPES


def _clone_const_in(recipe, const_value):
    """Return a copy of `recipe` with every `inputs[*].range_{{lo,hi}}`
    collapsed to `[const_value, const_value + 1e-3]`.  The small
    epsilon defeats the harness's `lo < hi` validator while keeping
    the input effectively constant for bf16/fp16 precision (the
    range is smaller than the output ULP for any reasonable
    accumulator magnitude).
    """
    out = dict(recipe)
    out["name"] = recipe["name"] + "_const_in"
    out["inputs"] = [
        {{**inp, "range_lo": const_value, "range_hi": const_value + 1e-3}}
        for inp in recipe.get("inputs", [])
    ]
    return out


_CONST = {const}

RECIPES = [_clone_const_in(_BASE_RECIPES[0], _CONST)]
'''


def _infer_base_module(base_path: Path) -> str:
    """Map `.../kernels/triton/foo.py` → `foo`.

    Assumes flat recipe layout under the recipes directory — the
    compare_correctness `Makefile` adds `kernels/triton/` (one
    level) to `PYTHONPATH` during AOT compile, so subdirectory
    recipes are not importable by a flat stem name.  Bases under
    a subdirectory (e.g. `_corpus/extracted/foo.py`) are rejected
    upstream in `_validate_base_shape`.
    """
    return base_path.stem


def _validate_base_shape(base_path: Path) -> None:
    """Fail loudly on recipe-file shapes this generator does not
    support.  Three invariants (see the script docstring for the
    methodology-level reasoning behind each):

      (a) The file lives directly under the recipes directory
          (no subdirectory — flat-layout assumption of
          `_infer_base_module`).  Subdirectory recipes would need
          `__init__.py` plumbing and PYTHONPATH wiring we do not
          currently handle.
      (b) A top-level `RECIPES = [...]` assignment is present.
          Every compare_correctness recipe file follows this
          convention; anything else is either stale extracted
          kernel source under `_corpus/` or a typo worth catching
          explicitly.
      (c) The `RECIPES` list has exactly one element.  The current
          corpus is single-recipe per file (empirically verified
          on every recipe as of 2026-04-22).  Multi-recipe files
          would silently drop all but index 0 through the
          `_BASE_RECIPES[0]` clone below — we fail at generation
          time so the user can split the base file into one-per
          siblings instead of getting a `_const_in` for only the
          first entry.
    """
    # (a) flat layout
    if "/" in str(base_path.parent.name) and base_path.parent.name in (
        "_corpus", "extracted", "__pycache__"):
        raise SystemExit(
            f"{base_path}: recipe lives under a subdirectory "
            f"(`{base_path.parent.name}`); this generator only supports "
            "recipes directly under `kernels/triton/`.  Move the base "
            "recipe to the flat layout or extend `_infer_base_module` "
            "with subdir → dotted-path mapping + `__init__.py` wiring.")

    # (b) top-level RECIPES assignment + (c) exactly-one-element
    src = base_path.read_text()
    tree = ast.parse(src, filename=str(base_path))
    recipes_assign = None
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for tgt in node.targets:
                if isinstance(tgt, ast.Name) and tgt.id == "RECIPES":
                    recipes_assign = node
                    break
    if recipes_assign is None:
        raise SystemExit(
            f"{base_path}: no top-level `RECIPES = [...]` assignment "
            "found; this tool only supports recipes that follow the "
            "standard template.")

    # The RHS ought to be a List literal; count its element count
    # syntactically so we do not execute the recipe file to find out.
    if isinstance(recipes_assign.value, ast.List):
        n = len(recipes_assign.value.elts)
        if n != 1:
            raise SystemExit(
                f"{base_path}: RECIPES has {n} entries; this generator "
                "only handles single-recipe files.  Split into one-recipe-"
                "per-file siblings before generating const_in probes.")


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__.split("\n\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("base_recipe", type=Path,
                    help="Path to the base recipe .py file "
                         "(under kernels/triton/).")
    ap.add_argument("--const", type=float, default=1.0,
                    help="Constant input value.  Default 1.0 "
                         "(trivial for sums: native output = N * 1.0).")
    ap.add_argument("--output", type=Path, default=None,
                    help="Output path for the generated sibling. "
                         "Defaults to `<base>_const_in.py` next to the "
                         "base recipe.")
    args = ap.parse_args()

    base_path: Path = args.base_recipe.resolve()
    if not base_path.is_file():
        print(f"error: {base_path} is not a file", file=sys.stderr)
        return 2
    if base_path.suffix != ".py":
        print(f"error: {base_path} is not a Python file", file=sys.stderr)
        return 2

    _validate_base_shape(base_path)

    base_module = _infer_base_module(base_path)
    base_name = base_path.stem
    recipes_dir = base_path.parent

    output_path: Path = args.output or (recipes_dir /
                                         (base_name + "_const_in.py"))
    if output_path.exists():
        print(f"error: {output_path} already exists; "
              "remove it or specify --output to overwrite deliberately",
              file=sys.stderr)
        return 2

    body = TEMPLATE.format(
        base_name=base_name,
        base_module=base_module,
        base_path=base_path.name,  # show as printed path, not absolute
        const=args.const,
    )
    output_path.write_text(body)
    print(f"wrote {output_path}")
    print(f"  base: {base_path}")
    print(f"  base_module: {base_module}")
    print(f"  const: {args.const}")
    print()
    print("Next steps (from transpiler/tools/compare_correctness/):")
    print(f"  1. Register `{output_path.stem}` in `Makefile`'s "
          "TRITON_KERNELS list.")
    print(f"  2. `make kernels/build/{output_path.stem}.gfx1250.co "
          f"kernels/build/{output_path.stem}.gfx942.co "
          f"kernels/build/{output_path.stem}.sidecar.json`.")
    print(f"  3. `LD_PRELOAD=./libsalmon_intercept.so "
          f"./compare_correctness --recipe={output_path.stem}`.")
    print(f"  4. If salmon diverges from native:  read the deviation "
          f"pattern per `hotswap/docs/learnings.md` 2026-04-22 "
          "('Diagnostic technique' entry) to classify the suspect "
          "lifter path.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
