; RUN: %llvm_mc -mcpu=gfx1250 %s -o %t.o && %ld_lld -shared %t.o -o %t.hsaco \
; RUN:   && %not %raise_cli %t.hsaco --target-isa=gfx1250 --emit-ir=scratch_refusal_kernel 2>&1 | %FileCheck %s --check-prefix=STDERR
;
; Lift refusal test for the FLAT scratch family
; (`scratch_load_*`, `scratch_store_*`, `scratch_atomic_*`). Pins the
; contractual loud-failure behaviour of the early branch in
; `transpiler/handle_flat.cpp` that is keyed on the
; `SIInstrFlags::FlatScratch` TSFlags bit (SIDefines.h bit 56; set by
; the `IsFlatScratch` field on every `FLAT_Scratch_*_Pseudo` in
; FLATInstructions.td).
;
; === Why this is a refusal and not a handler ===
;
; The principled lift of `scratch_*` is per-thread private-segment
; memory, which in IR is `addrspace(5)` (alloca / load / store).
; Salmon's compilation-target ABI deliberately does NOT request
; `flat_scratch_init` in the kernel descriptor — see the regression
; guard in `lit_tests/buffer_store_no_scratch_alloca/`, which
; explicitly forbids any `addrspace(5)` alloca surviving in the
; lifted IR. Reasoning recap (also captured in the FlatScratch
; comment block at the top of `handle_flat.cpp` and in
; `handle_mubuf.cpp`'s block on the legacy OOB sink):
;
;   * Any `addrspace(5)` alloca that survives PromoteMemToReg makes
;     the AMDGPU backend emit `.amdhsa_enable_private_segment 1` plus
;     `.amdhsa_private_segment_fixed_size > 0`.
;   * Salmon's KD models only the source ABI's user-SGPR set and does
;     NOT request `flat_scratch_init`, so on entry `FLAT_SCRATCH` is
;     undefined; any lifted flat-scratch access is a guaranteed fault
;     — silent miscompile of the entire kernel.
;
; The source kernel here uses inline asm to pin the SCRATCH encoding,
; but the same refusal applies verbatim to compiler-generated spills
; (the gfx1250 Triton FA-pipeline `attn_fwd` kernel in the kerneldex
; corpus requested its own `flat_scratch_init` + 64 B of
; `private_segment_fixed_size` for live-range spills, but the lifted
; module would get a fresh KD generated by the AMDGPU backend, and
; that KD inherits Salmon's no-flat-scratch-init policy).
;
; Closing this gap "for real" requires extending the Salmon ABI to
; request `flat_scratch_init` + a private-segment size in the
; generated KD — a cross-cutting design change well outside the scope
; of an instruction-level handler. The refusal here documents the
; gap, swaps the generic "Unsupported instruction" surface for a
; specific, audit-clean failure, and unblocks the kerneldex coverage
; signal so a future ABI extension has a single anchor point to flip.
;
; === What this fixture asserts ===
;
; Two things:
;
;   1. The raiser exits non-zero (`%not` inverts the exit code — the
;      test passes only when raise_cli actually failed).
;   2. The stderr diagnostic names the offending mnemonic
;      (`scratch_store_b32`), the encoding format (`FLAT`), and the
;      architecturally-specific rationale — crucially the back-pointer
;      to the `buffer_store_no_scratch_alloca` regression guard, so a
;      future reader tracing the failure has a single anchor for the
;      ABI-level design constraint. Also pins the
;      `flat_scratch_init` mention and the mnemonic-family token
;      (`scratch_*`) so a future diagnostic rewrite that drifted to a
;      generic wording would fail this fixture.
;
; raise_cli's failure-line format is fixed (raise_cli.cpp:213):
;   `kernel '<name>' failed to raise: <mnemonic> [<format>]
;    @offset=0x<offset> :: <detail>`
;
; The handler also emits an explicit `transpiler: FLAT scratch
; refused: ...` line; pinning that line keeps the diagnostic text
; from drifting into something less actionable for users who read
; raise_cli's stderr directly.

; The handler-side refusal line names the family, the ABI anchor, and
; the back-pointer to the regression-guard fixture.
; STDERR: transpiler: FLAT scratch refused: scratch_store_b32
; STDERR-SAME: flat_scratch_init
; STDERR-SAME: buffer_store_no_scratch_alloca

; The raise_cli failure line names the mnemonic, the encoding format,
; and the detailed rationale (same anchors, independently cited — a
; future split of stderr vs. the returned RaiseFailure must keep both
; sides audit-clean).
; STDERR: raise_cli: kernel 'scratch_refusal_kernel' failed to raise:
; STDERR-SAME: scratch_store_b32
; STDERR-SAME: [FLAT]
; STDERR-SAME: flat_scratch_init
; STDERR-SAME: buffer_store_no_scratch_alloca

	.amdgcn_target "amdgcn-amd-amdhsa--gfx1250"
	.amdhsa_code_object_version 6
	.text
	.globl	scratch_refusal_kernel
	.p2align	8
	.type	scratch_refusal_kernel,@function
scratch_refusal_kernel:
	s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
	s_load_b64 s[0:1], s[0:1], 0x0
	v_mul_u32_u24_e32 v1, 3, v0
	;;#ASMSTART
	scratch_store_b32 off, v1, off offset:0
	scratch_load_b32  v1, off, off offset:0
	
	;;#ASMEND
	s_wait_kmcnt 0x0
	global_store_b32 v0, v1, s[0:1] scale_offset
	s_endpgm
	.section	.rodata,"a",@progbits
	.p2align	6, 0x0
	.amdhsa_kernel scratch_refusal_kernel
		.amdhsa_kernarg_size 8
		.amdhsa_user_sgpr_count 2
		.amdhsa_user_sgpr_kernarg_segment_ptr 1
		.amdhsa_wavefront_size32 1
		.amdhsa_next_free_vgpr 2
		.amdhsa_next_free_sgpr 2
		.amdhsa_float_denorm_mode_32 3
		.amdhsa_inst_pref_size 1
	.end_amdhsa_kernel
	.text
	.p2alignl 7, 3214868480
	.fill 96, 4, 3214868480
	.text
	.amdgpu_metadata
---
amdhsa.kernels:
  - .args:
      - { .address_space:  global, .offset:         0, .size:           8, .value_kind:     global_buffer }
    .group_segment_fixed_size: 0
    .kernarg_segment_align: 8
    .kernarg_segment_size: 8
    .max_flat_workgroup_size: 1024
    .name:           scratch_refusal_kernel
    .private_segment_fixed_size: 0
    .sgpr_count:     2
    .symbol:         scratch_refusal_kernel.kd
    .vgpr_count:     2
    .wavefront_size: 32
amdhsa.version: [1, 2]
...

	.end_amdgpu_metadata
