#include "flat_addr.hpp"
#include "handlers.hpp"

#include "semop.hpp"
#include "llvm/ADT/SmallVector.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstring>
#include <map>
#include <optional>
#include <string>
#include <tuple>

using namespace llvm;

namespace transpiler {

namespace {

// Shared helper for the `_D16_HI` half-register-store lift shape.
//
// Both `GLOBAL_STORE_SHORT_D16_HI` and `FLAT_STORE_SHORT_D16_HI` have
// the same half-register selector baked into the opcode: store bits
// [31:16] of the source VGPR (the "high half") rather than [15:0].
// The lowered shape is `lshr i32 %src32, 16` followed by `trunc i32
// to i16` — InstCombine folds this pair to the backend-preferred
// sub-dword-extraction shape on every AMDGPU target.
//
// Kept namespace-local (rather than as a public helper) because the
// semantics are tied 1:1 to the FLAT family's sub-dword store lift
// inside this file.  DS family has its own structurally-identical
// emission in handle_ds.cpp (DS_WRITE_B16_D16_HI under
// `ds_st_d16_hi` / `ds_st_hi16_shr` breadcrumbs); MUBUF family has
// the load-side companion in handle_mubuf.cpp (via `d16Half=2` in
// `mubufClassify`).  Three addrspace-specific handlers, one
// conceptual operation; they intentionally do not share a helper
// because each resolves a different addressing / EXEC-gating
// context before this final step.
//
// Value-name breadcrumbs (`d16hi_shift` on the lshr, `d16hi_trunc`
// on the trunc) match the `ds_store_b16_d16_hi` fixture's naming
// convention in spirit (prefix-on-shift, prefix-on-trunc), adapted
// to the FLAT addrspace to keep lit patterns family-local.
Value *emitD16HiHalfTruncI16(RaiseContext &ctx, Value *src32) {
  Value *shifted = ctx.B.CreateLShr(src32,
                                     ConstantInt::get(ctx.i32Ty, 16),
                                     "d16hi_shift");
  return ctx.B.CreateTrunc(shifted, Type::getInt16Ty(ctx.C),
                            "d16hi_trunc");
}

} // namespace

HandlerResult handleFLAT(RaiseContext &ctx, const DecodedInst &di,
                        OpResolver &op) {
  HandlerResult hr;
  StringRef mn(di.mnemonic);
  SemOp sop = di.semOp;

  // ---------------------------------------------------------------------
  // FLAT scratch family (`scratch_load_*`, `scratch_store_*`,
  // `scratch_atomic_*`) — early documented refusal.
  //
  // Detected by the `SIInstrFlags::FlatScratch` TSFlags bit (set by the
  // `IsFlatScratch` field on `FLAT_Scratch_*_Pseudo` in
  // FLATInstructions.td); covers the entire scratch-segment FLAT
  // sub-family in one place rather than enumerating every width × access
  // SemOp. The mnemonic-prefix safety net is intentionally NOT used as
  // the primary signal: SIInstrFlags is the canonical, encoding-derived
  // discriminator and matches LLVM's own dispatch in SIInstrInfo.
  //
  // Why this is a refusal, not a handler:
  //
  //   The principled lift of `scratch_*` is per-thread private-segment
  //   memory, which in IR is `addrspace(5)` (alloca / load / store).
  //   Salmon's compilation target ABI deliberately does NOT request
  //   `flat_scratch_init` in the kernel descriptor — see the regression
  //   guard in `lit_tests/buffer_store_no_scratch_alloca/`, which
  //   explicitly forbids any `addrspace(5)` alloca surviving in the
  //   lifted IR. Reasoning recap (also captured in
  //   `handle_mubuf.cpp`'s comment block on the legacy OOB sink):
  //
  //     * Any `addrspace(5)` alloca that survives PromoteMemToReg makes
  //       the AMDGPU backend emit `.amdhsa_enable_private_segment 1`
  //       plus `.amdhsa_private_segment_fixed_size > 0`.
  //     * Salmon's KD models only the source ABI's user-SGPR set and
  //       does NOT request `flat_scratch_init`, so on entry
  //       `FLAT_SCRATCH` is undefined; any lifted flat-scratch access
  //       is a guaranteed fault — silent miscompile of the entire
  //       kernel.
  //
  // The source kernel (in this case the gfx1250 Triton FA-pipeline
  // attn_fwd) requested its own `flat_scratch_init` and 64 B of
  // `private_segment_fixed_size` for live-range spills, but the lifted
  // module gets a fresh KD generated by the AMDGPU backend — and that
  // KD will inherit Salmon's no-flat-scratch-init policy. We refuse
  // loudly rather than synthesise a fake addrspace(5) lowering that
  // would either fault at run time (no `flat_scratch_init`) OR re-open
  // the BUFFER_STORE OOB-sink failure mode the
  // `buffer_store_no_scratch_alloca` regression guard was put in place
  // to prevent.
  //
  // Closing this gap "for real" requires extending the Salmon ABI to
  // request `flat_scratch_init` + a private-segment size in the
  // generated KD — a cross-cutting design change well outside the scope
  // of an instruction-level handler. The refusal here documents the
  // gap, swaps the generic "Unsupported instruction" surface for a
  // specific, audit-clean failure, and unblocks the kerneldex coverage
  // signal so a future ABI extension has a single anchor point to flip.
  if (di.tsFlags & SIInstrFlags::FlatScratch) {
    llvm::errs()
        << "transpiler: FLAT scratch refused: " << di.mnemonic
        << " — Salmon's compilation-target KD does not request "
        << "flat_scratch_init (matching the buffer_store_no_scratch_alloca "
        << "regression guard); a principled lift via addrspace(5) alloca "
        << "would either fault at run time on the lifted KD or re-open the "
        << "FLAT_SCRATCH ABI gap. Refusing rather than emitting a fallback. "
        << "See handle_flat.cpp's FlatScratch comment block for the design "
        << "rationale and the ABI-extension that would be needed to lift it.\n";
    hr.failure = RaiseFailure::unsupportedShape(
        di, "FLAT",
        "scratch_* (FLAT scratch segment): Salmon's KD does not request "
        "flat_scratch_init, so a principled lift via addrspace(5) alloca "
        "would either fault at run time (no FLAT_SCRATCH base) OR "
        "re-introduce the regression the "
        "buffer_store_no_scratch_alloca lit guard prevents. Closing this "
        "gap requires extending the Salmon ABI to request flat_scratch_init "
        "in the generated KD — out of scope for an instruction-level "
        "handler. Refusing loudly rather than emitting a silent-miscompile "
        "fallback.");
    return hr;
  }

  if (sop == SemOp::GLOBAL_LOAD_USHORT || sop == SemOp::GLOBAL_LOAD_SHORT_D16_HI ||
      sop == SemOp::GLOBAL_LOAD_SSHORT || sop == SemOp::GLOBAL_LOAD_UBYTE ||
      sop == SemOp::GLOBAL_LOAD_SBYTE) {
    ParsedReg dest = op.dst();
    bool isByte = sop == SemOp::GLOBAL_LOAD_UBYTE || sop == SemOp::GLOBAL_LOAD_SBYTE;
    Type *loadTy = isByte ? ctx.i8Ty : Type::getInt16Ty(ctx.C);
    // The ISA only guarantees natural alignment for each sub-dword access:
    // 1 byte for byte loads, 2 bytes for short loads. Using the ABI default
    // alignment here was over-promising for buffers legitimately aligned
    // to the element size.
    Align loadAlign = Align(isByte ? 1 : 2);

    FlatAddr fa = decodeGlobalLoadAddr(ctx, di, op, isByte ? 1 : 2,
                                        "GLOBAL_LOAD sub-dword");
    Value *addr = fa.ptr;
    // SPE-gate the memory access itself, not just the VGPR write-back.
    // The store counterparts (GLOBAL_STORE_*, ~line 196 below) are
    // already wrapped in `emitUnderExec`; the asymmetric pre-2026-04-22
    // handling where loads fired on every target lane — including
    // WaveNative "phantom" lanes whose source-wave had no workitem at
    // this position — caused HIP error 700 "illegal memory access"
    // when phantom-lane pointer-arithmetic VGPRs held `undef` /
    // stale-VGPR-slot values that pointed outside any allocated
    // region. See `handle_flat.cpp::FLAT_LOAD_*` block comment below
    // (and the matching audit of sub-dword, dword, and FLAT_LOAD
    // variants) for the full rationale. `ctx.regs.writeReg32` (the
    // low-level alloca path) is called inside the body rather than
    // `ctx.writeReg32` (which would wrap the write in a nested
    // `emitUnderExec` — harmless but redundant IR).
    ctx.emitUnderExec([&] {
      Value *loaded = ctx.B.CreateAlignedLoad(loadTy, addr, loadAlign,
                                               "gload_sub");
      bool isUnsigned = sop == SemOp::GLOBAL_LOAD_UBYTE ||
                        sop == SemOp::GLOBAL_LOAD_USHORT;
      Value *ext = isUnsigned ? ctx.B.CreateZExt(loaded, ctx.i32Ty)
                              : ctx.B.CreateSExt(loaded, ctx.i32Ty);
      if (sop == SemOp::GLOBAL_LOAD_SHORT_D16_HI) {
        Value *prev = ctx.regs.readReg32(ctx.B, dest);
        ext = ctx.B.CreateOr(
            ctx.B.CreateAnd(prev, ConstantInt::get(ctx.i32Ty, 0xFFFF)),
            ctx.B.CreateShl(ext, 16), "d16hi");
      }
      ctx.regs.writeReg32(ctx.B, dest, ext);
    });
    hr.handled = true;
    return hr;
  }

  if (sop == SemOp::GLOBAL_LOAD_DWORD || sop == SemOp::GLOBAL_LOAD_DWORDX2 ||
      sop == SemOp::GLOBAL_LOAD_DWORDX3 || sop == SemOp::GLOBAL_LOAD_DWORDX4) {
    int loadDwords = 1;
    if (sop == SemOp::GLOBAL_LOAD_DWORDX2) loadDwords = 2;
    else if (sop == SemOp::GLOBAL_LOAD_DWORDX3) loadDwords = 3;
    else if (sop == SemOp::GLOBAL_LOAD_DWORDX4) loadDwords = 4;

    ParsedReg dest = op.dst();

    FlatAddr fa = decodeGlobalLoadAddr(ctx, di, op, loadDwords * 4,
                                        "GLOBAL_LOAD dword");
    Value *addr = fa.ptr;

    // Same SPE-gating rationale as the GLOBAL_LOAD sub-dword block
    // above: without `emitUnderExec` wrapping the `CreateLoad`, every
    // target lane — including WaveNative "phantom" lanes whose
    // pointer-arithmetic VGPRs hold `undef` / stale slot data —
    // dereferences the addr VGPR pair and faults at runtime (HIP
    // error 700).  For the vector-load case (`DWORDX{2,3,4}`), the
    // single load + N extract-write pairs all go inside one
    // emitUnderExec block so inactive lanes skip the whole sequence.
    ctx.emitUnderExec([&] {
      if (loadDwords == 1) {
        ctx.regs.writeReg32(
            ctx.B, dest,
            ctx.B.CreateBitCast(
                ctx.B.CreateLoad(ctx.f32Ty, addr, "gload"),
                ctx.i32Ty));
      } else {
        Type *vecTy = FixedVectorType::get(ctx.i32Ty, loadDwords);
        Value *loaded = ctx.B.CreateLoad(vecTy, addr, "gload");
        for (int d = 0; d < loadDwords; d++) {
          ParsedReg sub = dest;
          sub.baseIdx = dest.baseIdx + d;
          sub.width = 1;
          ctx.regs.writeReg32(
              ctx.B, sub,
              ctx.B.CreateExtractElement(loaded, ctx.B.getInt32(d)));
        }
      }
    });
    hr.handled = true;
    return hr;
  }

  if (sop == SemOp::GLOBAL_STORE_BYTE || sop == SemOp::GLOBAL_STORE_SHORT ||
      sop == SemOp::GLOBAL_STORE_SHORT_D16_HI || sop == SemOp::GLOBAL_STORE_DWORD ||
      sop == SemOp::GLOBAL_STORE_DWORDX2 || sop == SemOp::GLOBAL_STORE_DWORDX3 ||
      sop == SemOp::GLOBAL_STORE_DWORDX4) {
    int storeDwords = 1;
    int storeBits = 32;
    // `_D16_HI` variants store bits [31:16] of the source VGPR rather
    // than [15:0] — a half-register selector baked into the opcode
    // (AMDGPU ISA; see `global_store_d16_hi_b16` in
    // FLATInstructions.td and handle_ds.cpp's DS_WRITE_B16_D16_HI for
    // the existing DS-family precedent).  The compiler emits this
    // form to write the upper-16-bits half of a 32-bit value without
    // an explicit `v_lshrrev_b32` shift — idiomatic in the fp32→bf16
    // round-to-nearest-even epilogue (`v_add3_u32 v, bits, odd_bit,
    // 0x7fff` produces the RNE-biased sum in a 32-bit VGPR, and
    // `global_store_d16_hi_b16` writes its upper 16 bits = the bf16
    // result).  Pre-fix, `storeHiHalf=false` for
    // `GLOBAL_STORE_SHORT_D16_HI` was silently wrong: every bf16-cast-
    // store kernel (Triton's `.to(tl.bfloat16) + tl.store` shape, which
    // the observed-production `topk_forward_bisect_m_laneprobe` recipe
    // exercises with no cross-lane ops) stored the LOW 16 bits of the
    // biased sum, reading as NaN-ish (`0x7FFF`) for typical values.
    bool storeHiHalf = false;
    if (sop == SemOp::GLOBAL_STORE_DWORDX4) storeDwords = 4;
    else if (sop == SemOp::GLOBAL_STORE_DWORDX3) storeDwords = 3;
    else if (sop == SemOp::GLOBAL_STORE_DWORDX2) storeDwords = 2;
    else if (sop == SemOp::GLOBAL_STORE_DWORD) storeDwords = 1;
    else if (sop == SemOp::GLOBAL_STORE_SHORT ||
             sop == SemOp::GLOBAL_STORE_SHORT_D16_HI) {
      storeBits = 16;
      storeDwords = 0;
      storeHiHalf = (sop == SemOp::GLOBAL_STORE_SHORT_D16_HI);
    } else if (sop == SemOp::GLOBAL_STORE_BYTE) {
      storeBits = 8;
      storeDwords = 0;
    }

    // scale_offset on stores scales the per-lane vaddr by the access
    // element size. For sub-dword stores (byte/short) the element size
    // is 1 or 2 bytes; for dword/dwordx{2,3,4} it is 4, 8, 12, or 16
    // bytes — the compiler emits `global_store_dwordx4 … scale_offset`
    // with a lane-index vaddr to lower `out[tid] = vec4` patterns.
    int elemBytes = storeBits < 32 ? (storeBits / 8)
                                    : std::max(storeDwords, 1) * 4;
    FlatAddr fa =
        decodeGlobalStoreAddr(ctx, di, op, elemBytes, "GLOBAL_STORE");
    Value *addr = fa.ptr;
    ParsedReg stData = fa.stData;

    if (storeDwords == 0) {
      Value *src32 = ctx.regs.readReg32(ctx.B, stData);
      // `_D16_HI` variant routes through the shared half-register
      // helper that emits `lshr 16 + trunc to i16`; the non-
      // `_D16_HI` short / byte path takes a plain trunc to `memTy`.
      Value *val = storeHiHalf
                      ? emitD16HiHalfTruncI16(ctx, src32)
                      : ctx.B.CreateTrunc(
                            src32, Type::getIntNTy(ctx.C, storeBits));
      ctx.emitUnderExec([&] { ctx.B.CreateStore(val, addr); });
    } else if (storeDwords == 1) {
      Value *val = ctx.regs.readReg32(ctx.B, stData);
      ctx.emitUnderExec([&] { ctx.B.CreateStore(val, addr); });
    } else {
      auto *vecTy = FixedVectorType::get(ctx.i32Ty, storeDwords);
      Value *val = ctx.regs.readRegVec(ctx.B, stData, vecTy);
      ctx.emitUnderExec([&] { ctx.B.CreateStore(val, addr); });
    }
    hr.handled = true;
    return hr;
  }

  // ---------------------------------------------------------------------
  // gfx1250 async global → LDS load (FLAT VFLAT 0x5f-0x62 — b8 / b32 /
  // b64 / b128).
  //
  // Operand layout from `FLAT_Global_Load_LDS_Pseudo<…, IsAsync=1>`
  // (FLATInstructions.td:391-417) is identical across all four widths
  // (only the data byte size — and so the intrinsic ID — varies):
  //
  //   plain (4 srcs): vdst:VGPR_32, vaddr:VGPR_64,            offset, cpol
  //   SADDR (5 srcs): vdst:VGPR_32, saddr:SReg_64, vaddr:VGPR_32, offset, cpol
  //
  // `vdst` is in the *input* list (because `has_vdst = IsAsync = 1`)
  // and carries the per-lane LDS i32 base offset. The intrinsics
  // `int_amdgcn_global_load_async_to_lds_b{8,32,64,128}`
  // (IntrinsicsAMDGPU.td:3939-3946) all share signature
  // `AMDGPUAsyncGlobalLoadToLDS` (line 3904) and consume the LDS
  // pointer as `local_ptr_ty`, so we materialise it via `inttoptr i32
  // → ptr addrspace(3)`. Each lane fires its own write so the call
  // is wrapped in `emitUnderExec`; the intrinsic's
  // `IntrInaccessibleMemOrArgMemOnly` attribute keeps later passes
  // from sinking it across companion `s_wait_asynccnt` barriers.
  //
  // gfx942 has no asynchronous global→LDS DMA channel, so a cross-
  // target lift (gfx1250 → gfx942) is refused loudly. See the
  // SemOp's docstring in `semop.hpp` for the design rationale.
  if (sop == SemOp::GLOBAL_LOAD_ASYNC_TO_LDS_B8 ||
      sop == SemOp::GLOBAL_LOAD_ASYNC_TO_LDS_B32 ||
      sop == SemOp::GLOBAL_LOAD_ASYNC_TO_LDS_B64 ||
      sop == SemOp::GLOBAL_LOAD_ASYNC_TO_LDS_B128) {
    if (!ctx.targetIsa.hasTensorOps) {
      llvm::errs()
          << "transpiler: FLAT: " << di.mnemonic
          << " has no equivalent on the compilation target "
          << "(gfx1250 asynccnt unit; LLVM intrinsic "
          << "amdgcn.global.load.async.to.lds.b{8,32,64,128} is gated "
          << "by FeatureGFX1250Insts). A synthesised "
          << "global_load + ds_write pair would alter the wave's "
          << "memory ordering and asynccnt observable state — "
          << "refusing to emit a fallback.\n";
      hr.failure = RaiseFailure::unsupportedShape(
          di, "FLAT",
          "gfx1250-only async global→LDS DMA; no equivalent on "
          "non-gfx1250 compilation target (no asynccnt unit, no "
          "amdgcn.global.load.async.to.lds.b* intrinsic)");
      return hr;
    }

    bool isSaddr = false;
    if (op.nSrcs() == 5) {
      isSaddr = true;
    } else if (op.nSrcs() != 4) {
      hr.failure = RaiseFailure::unsupportedShape(
          di, "FLAT",
          "global_load_async_to_lds_b*: expected 4 srcs (plain) or "
          "5 srcs (SADDR) per FLAT_Global_Load_LDS_Pseudo<IsAsync=1>");
      return hr;
    }

    ParsedReg vdstPr = op.srcReg(0);
    if (vdstPr.kind != ParsedReg::VGPR) {
      hr.failure = RaiseFailure::unsupportedShape(
          di, "FLAT",
          "global_load_async_to_lds_b*: vdst (LDS-base operand) is "
          "not a VGPR");
      return hr;
    }
    Value *ldsOff = ctx.regs.readReg32(ctx.B, vdstPr);
    Type *ptrLDSTy = PointerType::get(ctx.C, /*addrspace=*/3);
    Value *ldsPtr = ctx.B.CreateIntToPtr(ldsOff, ptrLDSTy, "lds_ptr");

    Value *globalAddr = nullptr;
    unsigned immStart = 0;
    if (isSaddr) {
      ParsedReg saddrPr = op.srcReg(1);
      ParsedReg vaddrPr = op.srcReg(2);
      if (saddrPr.kind != ParsedReg::SGPR ||
          vaddrPr.kind != ParsedReg::VGPR) {
        hr.failure = RaiseFailure::unsupportedShape(
            di, "FLAT",
            "global_load_async_to_lds_b* SADDR: expected "
            "(SGPR_64, VGPR_32) for (saddr, vaddr)");
        return hr;
      }
      Value *saddr = ctx.regs.readReg64(ctx.B, saddrPr);
      Value *voff = ctx.B.CreateZExt(
          ctx.regs.readReg32(ctx.B, vaddrPr), ctx.i64Ty, "voff_zext");
      globalAddr = ctx.B.CreateAdd(saddr, voff, "saddr_vaddr");
      immStart = 3;
    } else {
      ParsedReg vaddrPr = op.srcReg(1);
      if (vaddrPr.kind != ParsedReg::VGPR) {
        hr.failure = RaiseFailure::unsupportedShape(
            di, "FLAT",
            "global_load_async_to_lds_b* plain: expected VGPR_64 "
            "for vaddr");
        return hr;
      }
      globalAddr = ctx.regs.readReg64(ctx.B, vaddrPr);
      immStart = 2;
    }

    int64_t flatOffset = 0;
    int64_t cpolImm = 0;
    bool sawOffset = false;
    for (unsigned k = immStart; k < op.nSrcs(); ++k) {
      if (!di.isImm(op.srcIdx(k))) continue;
      int64_t v = di.getImm(op.srcIdx(k));
      if (!sawOffset) {
        flatOffset = v;
        sawOffset = true;
      } else {
        cpolImm = v;
      }
    }

    Value *globalPtr = globalAddr;
    if (globalPtr->getType() != ctx.ptrGlobalTy)
      globalPtr = ctx.B.CreateIntToPtr(globalPtr, ctx.ptrGlobalTy);

    Intrinsic::ID iid;
    switch (sop) {
    case SemOp::GLOBAL_LOAD_ASYNC_TO_LDS_B8:
      iid = Intrinsic::amdgcn_global_load_async_to_lds_b8; break;
    case SemOp::GLOBAL_LOAD_ASYNC_TO_LDS_B32:
      iid = Intrinsic::amdgcn_global_load_async_to_lds_b32; break;
    case SemOp::GLOBAL_LOAD_ASYNC_TO_LDS_B64:
      iid = Intrinsic::amdgcn_global_load_async_to_lds_b64; break;
    case SemOp::GLOBAL_LOAD_ASYNC_TO_LDS_B128:
      iid = Intrinsic::amdgcn_global_load_async_to_lds_b128; break;
    default:
      llvm_unreachable("dispatch matched async-to-LDS family but width SemOp "
                       "fell through the switch");
    }
    Function *fn = Intrinsic::getOrInsertDeclaration(&ctx.M, iid);
    Value *offsetArg = ConstantInt::get(ctx.i32Ty, flatOffset);
    Value *cpolArg = ConstantInt::get(ctx.i32Ty, cpolImm);
    ctx.emitUnderExec([&] {
      ctx.B.CreateCall(fn, {globalPtr, ldsPtr, offsetArg, cpolArg});
    });

    hr.handled = true;
    return hr;
  }

  // ---------------------------------------------------------------------
  // gfx1250 FLAT VMEM prefetch (VFLAT 0x05D — global_prefetch_b8).
  //
  // Operand layout from `FLAT_Prefetch_Pseudo` (FLATInstructions.td
  // :525-553) — note `has_vdst = 0`, so there is no dst slot:
  //
  //   plain (3 srcs): vaddr:VGPR_64,            offset, cpol
  //   SADDR (4 srcs): saddr:SReg_64, vaddr:VGPR_32, offset, cpol
  //
  // Lifts to `int_amdgcn_global_prefetch(globalPtr, cpol)`
  // (IntrinsicsAMDGPU.td:3211); the FLAT `flat_offset` is folded
  // onto the pointer via a non-inbounds GEP before the call (the
  // intrinsic itself takes no offset operand). The call sits
  // OUTSIDE `emitUnderExec` because the intrinsic carries the EXEC
  // mask implicitly through `IntrInaccessibleMemOrArgMemOnly` — a
  // hint with no observable side effect on inactive lanes, so an
  // extra `if-spe-active` guard would gratuitously inflate IR for
  // what hardware executes as a single broadcast hint.
  //
  // gfx942 has no VMEM-prefetch encoding (the intrinsic is gated by
  // `HasVmemPrefInsts`, only set on gfx1250+), so a cross-target
  // lift is refused loudly. See the SemOp's docstring in
  // `semop.hpp` for the design rationale.
  if (sop == SemOp::GLOBAL_PREFETCH_B8) {
    if (!ctx.targetIsa.hasTensorOps) {
      llvm::errs()
          << "transpiler: FLAT: " << di.mnemonic
          << " has no equivalent on the compilation target "
          << "(gfx1250 VMEM-prefetch unit; LLVM intrinsic "
          << "amdgcn.global.prefetch is gated by HasVmemPrefInsts, "
          << "only set on gfx1250+). The closest sibling "
          << "amdgcn.s.prefetch.data requires a uniform SGPR "
          << "pointer which we cannot prove for the divergent "
          << "VGPR address used here without divergence "
          << "analysis — refusing to emit a fallback or silently "
          << "drop the hint.\n";
      hr.failure = RaiseFailure::unsupportedShape(
          di, "FLAT",
          "gfx1250-only VMEM prefetch (HasVmemPrefInsts); no "
          "equivalent on non-gfx1250 compilation target. The "
          "amdgcn.s.prefetch.data sibling requires a uniform "
          "pointer (the VMEM prefetch is divergent), and a silent "
          "drop would mask both the cross-target capability gap "
          "and any pipeline-tuning regression downstream.");
      return hr;
    }

    bool isSaddr = false;
    if (op.nSrcs() == 4) {
      isSaddr = true;
    } else if (op.nSrcs() != 3) {
      hr.failure = RaiseFailure::unsupportedShape(
          di, "FLAT",
          "global_prefetch_b8: expected 3 srcs (plain) or 4 srcs "
          "(SADDR) per FLAT_Prefetch_Pseudo");
      return hr;
    }

    Value *globalAddr = nullptr;
    unsigned immStart = 0;
    if (isSaddr) {
      ParsedReg saddrPr = op.srcReg(0);
      ParsedReg vaddrPr = op.srcReg(1);
      if (saddrPr.kind != ParsedReg::SGPR ||
          vaddrPr.kind != ParsedReg::VGPR) {
        hr.failure = RaiseFailure::unsupportedShape(
            di, "FLAT",
            "global_prefetch_b8 SADDR: expected (SGPR_64, VGPR_32) "
            "for (saddr, vaddr)");
        return hr;
      }
      Value *saddr = ctx.regs.readReg64(ctx.B, saddrPr);
      Value *voff = ctx.B.CreateZExt(
          ctx.regs.readReg32(ctx.B, vaddrPr), ctx.i64Ty, "voff_zext");
      globalAddr = ctx.B.CreateAdd(saddr, voff, "saddr_vaddr");
      immStart = 2;
    } else {
      ParsedReg vaddrPr = op.srcReg(0);
      if (vaddrPr.kind != ParsedReg::VGPR) {
        hr.failure = RaiseFailure::unsupportedShape(
            di, "FLAT",
            "global_prefetch_b8 plain: expected VGPR_64 for vaddr");
        return hr;
      }
      globalAddr = ctx.regs.readReg64(ctx.B, vaddrPr);
      immStart = 1;
    }

    int64_t flatOffset = 0;
    int64_t cpolImm = 0;
    bool sawOffset = false;
    for (unsigned k = immStart; k < op.nSrcs(); ++k) {
      if (!di.isImm(op.srcIdx(k))) continue;
      int64_t v = di.getImm(op.srcIdx(k));
      if (!sawOffset) {
        flatOffset = v;
        sawOffset = true;
      } else {
        cpolImm = v;
      }
    }

    Value *globalPtr = globalAddr;
    if (globalPtr->getType() != ctx.ptrGlobalTy)
      globalPtr = ctx.B.CreateIntToPtr(globalPtr, ctx.ptrGlobalTy);
    if (flatOffset != 0)
      globalPtr = ctx.B.CreateGEP(ctx.i8Ty, globalPtr,
                                   ctx.B.getInt64(flatOffset),
                                   "prefetch_addr");

    Function *fn = Intrinsic::getOrInsertDeclaration(
        &ctx.M, Intrinsic::amdgcn_global_prefetch);
    Value *cpolArg = ConstantInt::get(ctx.i32Ty, cpolImm);
    ctx.B.CreateCall(fn, {globalPtr, cpolArg});

    hr.handled = true;
    return hr;
  }

  // flat_load/flat_store — same structure as global but uses flat address
  // space on the plain-VGPR64 form (gfx9/10/11) and global address space
  // on the gfx12+ SADDR form.  Detection is by operand shape, matching
  // `decodeGlobalLoadAddr`'s discriminator but with address-space
  // semantics preserved per case (the shared decoder unconditionally
  // casts to `ctx.ptrGlobalTy` which is addrspace(1); we route through
  // it only for the SADDR form where that cast is hardware-correct).
  if (sop == SemOp::FLAT_LOAD_USHORT || sop == SemOp::FLAT_LOAD_SSHORT ||
      sop == SemOp::FLAT_LOAD_UBYTE || sop == SemOp::FLAT_LOAD_SBYTE) {
    ParsedReg dest = op.dst();
    bool isByte = sop == SemOp::FLAT_LOAD_UBYTE || sop == SemOp::FLAT_LOAD_SBYTE;
    Value *addr = nullptr;
    // SADDR form: saddr(SGPR64), vaddr(VGPR32), [scale_offset] [offset:imm]
    // — semantically a global_load (SGPR base + per-lane VGPR offset),
    // so delegate to the shared decoder and accept its addrspace(1)
    // conversion.
    if (op.nSrcs() >= 2 && op.isSrcReg(0) && op.isSrcReg(1) &&
        op.srcReg(0).kind == ParsedReg::SGPR &&
        op.srcReg(1).kind == ParsedReg::VGPR) {
      FlatAddr fa = decodeGlobalLoadAddr(ctx, di, op, isByte ? 1 : 2,
                                          "FLAT_LOAD sub-dword (SADDR)");
      addr = fa.ptr;
    } else {
      // Plain-flat form: VGPR64 holds the full per-lane flat address.
      // Preserve addrspace(0) so the backend re-emits `flat_load_*` on
      // targets where plain-flat may legitimately reach LDS or private
      // (gfx9/10/11 AMDGPU lowering keys off the AS to choose between
      // flat/global/ds/scratch load classes).
      addr = ctx.regs.readReg64(ctx.B, op.srcReg(0));
      Type *ptrFlatTy = PointerType::get(ctx.C, 0);
      if (addr->getType() != ptrFlatTy)
        addr = ctx.B.CreateIntToPtr(addr, ptrFlatTy);
      int64_t memOffset = 0;
      for (unsigned k = 1; k < op.nSrcs(); k++)
        if (di.isImm(op.srcIdx(k)) && di.getImm(op.srcIdx(k)) != 0)
          memOffset = di.getImm(op.srcIdx(k));
      if (memOffset != 0)
        addr = ctx.B.CreateInBoundsGEP(ctx.i8Ty, addr,
                                        ctx.B.getInt64(memOffset));
    }
    Type *loadTy = isByte ? ctx.i8Ty : Type::getInt16Ty(ctx.C);
    // SPE-gate the memory access itself. Same rationale as the
    // GLOBAL_LOAD sub-dword block above: unguarded loads fault on
    // WaveNative phantom lanes whose pointer VGPRs hold `undef` or
    // stale data. FLAT (plain-VGPR64) loads can legitimately reach
    // LDS / private / global — an out-of-range phantom-lane pointer
    // will still page-fault in whichever aperture it lands in.
    ctx.emitUnderExec([&] {
      Value *loaded = ctx.B.CreateLoad(loadTy, addr, "flat_load_sub");
      bool isUnsigned = sop == SemOp::FLAT_LOAD_UBYTE ||
                        sop == SemOp::FLAT_LOAD_USHORT;
      Value *ext = isUnsigned ? ctx.B.CreateZExt(loaded, ctx.i32Ty)
                              : ctx.B.CreateSExt(loaded, ctx.i32Ty);
      ctx.regs.writeReg32(ctx.B, dest, ext);
    });
    hr.handled = true;
    return hr;
  }

  if (sop == SemOp::FLAT_LOAD_DWORD || sop == SemOp::FLAT_LOAD_DWORDX2 ||
      sop == SemOp::FLAT_LOAD_DWORDX3 || sop == SemOp::FLAT_LOAD_DWORDX4) {
    int loadDwords = 1;
    if (sop == SemOp::FLAT_LOAD_DWORDX2) loadDwords = 2;
    else if (sop == SemOp::FLAT_LOAD_DWORDX4) loadDwords = 4;
    else if (sop == SemOp::FLAT_LOAD_DWORDX3) loadDwords = 3;

    // Two operand-shape variants, with distinct address-space semantics:
    //
    //   (plain)  vaddr:VGPR64, [imms]
    //              — gfx9/10/11 `flat_load_dword`: VGPR64 holds a full
    //              per-lane flat address that may legitimately reach
    //              LDS or private; lift as addrspace(0) so the target
    //              backend can re-emit `flat_load_*`.
    //
    //   (SADDR)  saddr:SGPR64, vaddr:VGPR32, [scale_offset] [offset:imm]
    //              — gfx12+ `flat_load_b32 … scale_offset`: uniform
    //              SGPR64 base + per-lane VGPR32 offset, semantically
    //              identical to `global_load_dword`'s SADDR form (the
    //              hardware's scale-offset + signed-imm arithmetic can
    //              only reach globally-allocated memory, which the
    //              compiler encodes by choosing this variant).  Lift
    //              as addrspace(1) via the shared `decodeGlobalLoadAddr`
    //              helper so the target backend re-emits
    //              `global_load_*` with matching scale-offset arithmetic.
    //
    // Before the SADDR arm was added, the handler took `op.srcReg(0)`
    // as a 64-bit pointer unconditionally.  On the SADDR form that
    // silently picked up the saddr SGPR pair as the full address and
    // DROPPED the per-lane VGPR offset, producing a kernel where every
    // lane addresses the same memory location (observable on the
    // `rcp_sqrt_kernel` gfx1250 fixture: 256 output lanes all reading
    // `in[0x206/4] = in[518]` regardless of tid — see the
    // `Gfx1250Gpu.RcpSqrt` regression gate in `tests/gfx1250_gpu_test.cpp`).
    // The shape discriminator below (`op.srcReg(0).kind == SGPR` AND
    // `op.srcReg(1).kind == VGPR`) matches `decodeGlobalLoadAddr`'s
    // inner predicate but keeps the plain-form AS choice local — the
    // shared helper unconditionally casts its result to addrspace(1),
    // which is correct for SADDR and wrong for plain-flat on pre-gfx12.
    Value *addr = nullptr;
    if (op.nSrcs() >= 2 && op.isSrcReg(0) && op.isSrcReg(1) &&
        op.srcReg(0).kind == ParsedReg::SGPR &&
        op.srcReg(1).kind == ParsedReg::VGPR) {
      FlatAddr fa = decodeGlobalLoadAddr(ctx, di, op, loadDwords * 4,
                                          "FLAT_LOAD dword (SADDR)");
      addr = fa.ptr;
    } else {
      addr = ctx.regs.readReg64(ctx.B, op.srcReg(0));
      Type *ptrFlatTy = PointerType::get(ctx.C, 0);
      if (addr->getType() != ptrFlatTy)
        addr = ctx.B.CreateIntToPtr(addr, ptrFlatTy);
      int64_t memOffset = 0;
      for (unsigned k = 1; k < op.nSrcs(); k++)
        if (di.isImm(op.srcIdx(k)) && di.getImm(op.srcIdx(k)) != 0)
          memOffset = di.getImm(op.srcIdx(k));
      if (memOffset != 0)
        addr = ctx.B.CreateInBoundsGEP(ctx.i8Ty, addr,
                                        ctx.B.getInt64(memOffset));
    }

    ParsedReg dest = op.dst();
    // SPE-gate the memory access itself (same rationale as
    // GLOBAL_LOAD dword above).  For DWORDX{2,3,4} the single vector
    // load + N element-extract writes all live inside one
    // `emitUnderExec` block so inactive lanes skip the whole
    // sequence and the store phase's VGPR consumers observe the
    // alloca state from the most recent active write.
    ctx.emitUnderExec([&] {
      if (loadDwords == 1) {
        ctx.regs.writeReg32(
            ctx.B, dest,
            ctx.B.CreateBitCast(
                ctx.B.CreateLoad(ctx.f32Ty, addr, "flat_load"),
                ctx.i32Ty));
      } else {
        Type *vecTy = FixedVectorType::get(ctx.i32Ty, loadDwords);
        Value *loaded = ctx.B.CreateLoad(vecTy, addr, "flat_load");
        for (int d = 0; d < loadDwords; d++) {
          ParsedReg sub = dest;
          sub.baseIdx = dest.baseIdx + d;
          sub.width = 1;
          ctx.regs.writeReg32(
              ctx.B, sub,
              ctx.B.CreateExtractElement(loaded, ctx.B.getInt32(d)));
        }
      }
    });
    hr.handled = true;
    return hr;
  }

  if (sop == SemOp::FLAT_STORE_DWORD || sop == SemOp::FLAT_STORE_DWORDX2 ||
      sop == SemOp::FLAT_STORE_DWORDX3 || sop == SemOp::FLAT_STORE_DWORDX4 ||
      sop == SemOp::FLAT_STORE_BYTE || sop == SemOp::FLAT_STORE_SHORT ||
      sop == SemOp::FLAT_STORE_SHORT_D16_HI) {
    int storeDwords = 1;
    int storeBits = 32;
    // `FLAT_STORE_SHORT_D16_HI` stores bits [31:16] of the source
    // VGPR, not [15:0] — same half-register selector as
    // `GLOBAL_STORE_SHORT_D16_HI` above; see the comment block on
    // the GLOBAL_STORE_ branch for the full rationale (bf16 RNE
    // epilogue, pre-fix miscompile shape, etc.).
    bool storeHiHalf = false;
    if (sop == SemOp::FLAT_STORE_DWORDX4) storeDwords = 4;
    else if (sop == SemOp::FLAT_STORE_DWORDX3) storeDwords = 3;
    else if (sop == SemOp::FLAT_STORE_DWORDX2) storeDwords = 2;
    else if (sop == SemOp::FLAT_STORE_DWORD) storeDwords = 1;
    else if (sop == SemOp::FLAT_STORE_SHORT ||
             sop == SemOp::FLAT_STORE_SHORT_D16_HI) {
      storeBits = 16; storeDwords = 0;
      storeHiHalf = (sop == SemOp::FLAT_STORE_SHORT_D16_HI);
    }
    else if (sop == SemOp::FLAT_STORE_BYTE) { storeBits = 8; storeDwords = 0; }

    // Two operand-shape variants with distinct AS semantics; mirror
    // the FLAT_LOAD_DWORD handler's case split.  For stores:
    //
    //   (plain)  vaddr:VGPR64, vdata:VGPR*, [imms]            → addrspace(0)
    //   (SADDR)  vaddr:VGPR32, vdata:VGPR*, saddr:SGPR64, ... → addrspace(1)
    //
    // See the FLAT_LOAD_DWORD comment block above for the full
    // derivation and rcp_sqrt_kernel regression anchor.
    int elemBytes = storeBits < 32 ? (storeBits / 8)
                                    : std::max(storeDwords, 1) * 4;
    Value *addr = nullptr;
    ParsedReg stData;
    if (op.nSrcs() >= 3 && op.isSrcReg(0) && op.isSrcReg(1) &&
        op.isSrcReg(2) &&
        op.srcReg(0).kind == ParsedReg::VGPR &&
        op.srcReg(1).kind == ParsedReg::VGPR &&
        op.srcReg(2).kind == ParsedReg::SGPR) {
      FlatAddr fa = decodeGlobalStoreAddr(ctx, di, op, elemBytes,
                                           "FLAT_STORE (SADDR)");
      addr = fa.ptr;
      stData = fa.stData;
    } else {
      addr = ctx.regs.readReg64(ctx.B, op.srcReg(0));
      Type *ptrFlatTy = PointerType::get(ctx.C, 0);
      if (addr->getType() != ptrFlatTy)
        addr = ctx.B.CreateIntToPtr(addr, ptrFlatTy);
      int64_t memOffset = 0;
      for (unsigned k = 2; k < op.nSrcs(); k++)
        if (di.isImm(op.srcIdx(k)) && di.getImm(op.srcIdx(k)) != 0)
          memOffset = di.getImm(op.srcIdx(k));
      if (memOffset != 0)
        addr = ctx.B.CreateInBoundsGEP(ctx.i8Ty, addr,
                                        ctx.B.getInt64(memOffset));
      stData = op.srcReg(1);
    }
    if (storeDwords == 0) {
      Value *src32 = ctx.regs.readReg32(ctx.B, stData);
      // See emitD16HiHalfTruncI16's doc block for the shared-helper
      // rationale; this branch mirrors the GLOBAL_STORE path above
      // so both FLAT and GLOBAL `_D16_HI` variants graduate through
      // the same emission shape.
      Value *val = storeHiHalf
                      ? emitD16HiHalfTruncI16(ctx, src32)
                      : ctx.B.CreateTrunc(
                            src32, Type::getIntNTy(ctx.C, storeBits));
      ctx.emitUnderExec([&] { ctx.B.CreateStore(val, addr); });
    } else if (storeDwords == 1) {
      Value *val = ctx.regs.readReg32(ctx.B, stData);
      ctx.emitUnderExec([&] { ctx.B.CreateStore(val, addr); });
    } else {
      auto *vecTy = FixedVectorType::get(ctx.i32Ty, storeDwords);
      Value *val = ctx.regs.readRegVec(ctx.B, stData, vecTy);
      ctx.emitUnderExec([&] { ctx.B.CreateStore(val, addr); });
    }
    hr.handled = true;
    return hr;
  }

  // flat_atomic_* — same as global_atomic but flat address space
  if (sop >= SemOp::FLAT_ATOMIC_ADD && sop <= SemOp::FLAT_ATOMIC_ADD_F32) {
    // Contract: the RTN/non-RTN collapse in OpcodeMap relies on
    // IsAtomicRet <=> (numDefs > 0) to decide result writeback below.
    assert(((di.tsFlags & SIInstrFlags::IsAtomicRet) != 0) == (di.numDefs > 0) &&
           "flat atomic: IsAtomicRet disagrees with numDefs");
    // Two operand-shape variants, mirroring the FLAT_LOAD/STORE case
    // split and the GLOBAL_ATOMIC block below:
    //
    //   (plain)  vaddr:VGPR64, vdata:VGPR*, [imms] → addrspace(0)
    //              gfx9/10/11 `flat_atomic_add v[A:B], vData, off[,offset]`:
    //              VGPR64 holds a full per-lane flat address that may
    //              legitimately reach LDS/private/global; preserve
    //              addrspace(0) so the backend re-emits `flat_atomic_*`
    //              on targets where plain-flat is still valid.
    //
    //   (SADDR)  vaddr:VGPR32, vdata:VGPR*, saddr:SGPR64,
    //            [scale_offset] [offset:imm] → addrspace(1)
    //              gfx12+ `flat_atomic_* vAddr, vData, s[A:B]
    //              [scale_offset]`: scale-offset + signed-imm
    //              arithmetic can only reach globally-allocated memory
    //              (same semantic-narrowing as FLAT_LOAD/STORE SADDR),
    //              so delegate to `decodeGlobalStoreAddr` which casts
    //              to `ctx.ptrGlobalTy` (addrspace(1)) and lets the
    //              backend re-emit `global_atomic_*` with matching
    //              scale-offset arithmetic.
    //
    // Before this split, the handler hard-coded the plain shape and
    // used a "first non-zero imm wins" scan that misidentified the
    // CPol operand (packed scale_offset + scope bits) as the signed
    // offset field.  The bug is DORMANT today — no recipe in the
    // compare_correctness Triton corpus emits gfx12+ `flat_atomic_*`
    // (Triton's gfx1250 codegen prefers `global_atomic_*` whenever it
    // knows the buffer lives in global) — but it's the identical
    // class that bit GLOBAL_ATOMIC (see that block's comment for the
    // `sum_bitmatrix_rows_u32` failure and the
    // `Gfx1250Gpu.SumBitmatrixRowsU32` regression gate).  Fixed here
    // for symmetry to close the "handler assumes operand shape that
    // varies by subtarget" bug class across FLAT_LOAD / FLAT_STORE /
    // FLAT_ATOMIC / GLOBAL_LOAD / GLOBAL_STORE / GLOBAL_ATOMIC — all
    // six now route SADDR through the shared decoder.
    Value *addr = nullptr;
    ParsedReg stData;
    const bool isSaddr = op.nSrcs() >= 3 && op.isSrcReg(0) &&
                         op.isSrcReg(1) && op.isSrcReg(2) &&
                         op.srcReg(0).kind == ParsedReg::VGPR &&
                         op.srcReg(1).kind == ParsedReg::VGPR &&
                         op.srcReg(2).kind == ParsedReg::SGPR;
    if (isSaddr) {
      FlatAddr fa = decodeGlobalStoreAddr(ctx, di, op, /*elemBytes=*/4,
                                           "FLAT_ATOMIC (SADDR)");
      addr = fa.ptr;
      stData = fa.stData;
    } else {
      ParsedReg addrReg = op.srcReg(0);
      addr = ctx.regs.readReg64(ctx.B, addrReg);
      Type *ptrFlatTy = PointerType::get(ctx.C, 0);
      if (addr->getType() != ptrFlatTy) addr = ctx.B.CreateIntToPtr(addr, ptrFlatTy);
      int64_t memOffset = 0;
      unsigned dataIdx = 1;
      for (unsigned k = 1; k < op.nSrcs(); k++) {
        if (di.isImm(op.srcIdx(k)) && di.getImm(op.srcIdx(k)) != 0)
          memOffset = di.getImm(op.srcIdx(k));
        else if (di.isReg(op.srcIdx(k)))
          dataIdx = k;
      }
      if (memOffset != 0) addr = ctx.B.CreateInBoundsGEP(ctx.i8Ty, addr, ctx.B.getInt64(memOffset));
      stData = op.srcReg(dataIdx);
    }
    Value *data = ctx.regs.readReg32(ctx.B, stData);

    if (sop == SemOp::FLAT_ATOMIC_CMPSWAP) {
      // CMPSWAP's vdata is a 2-vgpr pair (cmp, new); read low half as
      // cmpVal and the adjacent baseIdx+1 as newVal.
      Value *cmpVal = data;
      ParsedReg newReg = stData; newReg.baseIdx += 1; newReg.width = 1;
      Value *newVal = ctx.regs.readReg32(ctx.B, newReg);
      ctx.emitUnderExec([&] {
        auto *cas = ctx.B.CreateAtomicCmpXchg(
            addr, cmpVal, newVal, MaybeAlign(),
            AtomicOrdering::SequentiallyConsistent,
            AtomicOrdering::SequentiallyConsistent);
        if (di.numDefs > 0)
          ctx.regs.writeReg32(ctx.B, op.dst(),
                              ctx.B.CreateExtractValue(cas, 0));
      });
      hr.handled = true;
    return hr;
    }

    AtomicRMWInst::BinOp atomicOp;
    Type *atomicTy = ctx.i32Ty;
    bool isFP = false;
    switch (sop) {
    case SemOp::FLAT_ATOMIC_ADD:  atomicOp = AtomicRMWInst::Add; break;
    case SemOp::FLAT_ATOMIC_SUB:  atomicOp = AtomicRMWInst::Sub; break;
    case SemOp::FLAT_ATOMIC_AND:  atomicOp = AtomicRMWInst::And; break;
    case SemOp::FLAT_ATOMIC_OR:   atomicOp = AtomicRMWInst::Or; break;
    case SemOp::FLAT_ATOMIC_XOR:  atomicOp = AtomicRMWInst::Xor; break;
    case SemOp::FLAT_ATOMIC_SMIN: atomicOp = AtomicRMWInst::Min; break;
    case SemOp::FLAT_ATOMIC_SMAX: atomicOp = AtomicRMWInst::Max; break;
    case SemOp::FLAT_ATOMIC_UMIN: atomicOp = AtomicRMWInst::UMin; break;
    case SemOp::FLAT_ATOMIC_UMAX: atomicOp = AtomicRMWInst::UMax; break;
    case SemOp::FLAT_ATOMIC_SWAP: atomicOp = AtomicRMWInst::Xchg; break;
    case SemOp::FLAT_ATOMIC_ADD_F32:
      atomicOp = AtomicRMWInst::FAdd; isFP = true;
      data = ctx.B.CreateBitCast(data, ctx.f32Ty); atomicTy = ctx.f32Ty; break;
    default:
      llvm::errs() << "transpiler: Unhandled flat atomic: " << mn << "\n";
      hr.failure = RaiseFailure::unsupportedShape(di, "FLAT",
                                                   "unhandled flat atomic");
      return hr;
    }
    ctx.emitUnderExec([&] {
      auto *rmw = ctx.B.CreateAtomicRMW(
          atomicOp, addr, data, MaybeAlign(),
          AtomicOrdering::SequentiallyConsistent);
      if (di.numDefs > 0) {
        Value *retVal = rmw;
        if (isFP) retVal = ctx.B.CreateBitCast(retVal, ctx.i32Ty);
        ctx.regs.writeReg32(ctx.B, op.dst(), retVal);
      }
    });
    hr.handled = true;
    return hr;
  }

  // ---- Global atomics ----
  if (sop >= SemOp::GLOBAL_ATOMIC_ADD && sop <= SemOp::GLOBAL_ATOMIC_PK_ADD_F16) {
    assert(((di.tsFlags & SIInstrFlags::IsAtomicRet) != 0) == (di.numDefs > 0) &&
           "global atomic: IsAtomicRet disagrees with numDefs");
    // Delegate addressing to `decodeGlobalStoreAddr`.  Global atomics
    // share the store's operand shape — (vaddr, vdata, [saddr], [imms]) —
    // and we reuse the exact same decoder to get both shape variants
    // handled consistently:
    //
    //   (plain)  vaddr:VGPR64, vdata:VGPR*, [imms]
    //   (SADDR)  vaddr:VGPR32, vdata:VGPR*, saddr:SGPR64,
    //            [scale_offset] [offset:imm]
    //
    // Before this switch, the handler hard-coded the plain shape
    // (`readReg64(srcReg(0))`) AND used a heuristic "first non-zero imm
    // wins" scan to pick up the signed offset.  Two bugs compounded on
    // `_sum_bitmatrix_rows`'s
    //   global_atomic_add_u32 v1, v0, s[4:5] scale_offset scope:SCOPE_DEV
    // — the SADDR form:
    //
    //   (1) `op.srcReg(0)` is VGPR32 `v1` (the vaddr offset), not a
    //       pointer; reading it as a VGPR64 pair pulled in v2 as the
    //       high half and produced garbage.
    //   (2) After the saddr SGPR, the CPol operand carries the
    //       `scale_offset` bit + scope bits packed into a non-zero
    //       immediate (0x810 = 2064 for `scale_offset scope:SCOPE_DEV`);
    //       "first non-zero imm wins" mistook that for the signed
    //       offset field and added a 2064-byte GEP before the atomic,
    //       far past the 32-element `Out` buffer.
    //   (3) The same loop's "last reg-valued src = data" heuristic
    //       then selected the SGPR saddr (s[4:5] = Out pointer) as the
    //       data to atomic-add, instead of the VGPR vdata (v0 = the
    //       popcount sum).
    //
    // Net device-visible symptom: `HIP error 700 (illegal memory
    // access)` on every launch of `sum_bitmatrix_rows_u32` (and the
    // `_nw4` variant) — the atomic fired at the wrong address with
    // the wrong value.  `decodeGlobalStoreAddr` handles the shape
    // discriminator and uses `firstImmOffset` (FIRST imm, regardless
    // of value) for the offset field, so CPol no longer leaks into
    // the offset lookup.  See `hotswap/docs/learnings.md` entry
    // "2026-04-23 — global_atomic SADDR form silently miscompiled"
    // for the full investigation and the regression gate
    // (`Gfx1250Gpu.SumBitmatrixRowsU32`).
    //
    // Element size for `scale_offset`: every atomic in the SemOp range
    // [GLOBAL_ATOMIC_ADD, GLOBAL_ATOMIC_PK_ADD_F16] operates on a
    // 32-bit memory slot (the 64-bit `_X2` variants are outside this
    // range), so elemBytes=4 is correct for all of
    //   ADD/SUB/AND/OR/XOR/MIN/MAX/SWAP/ADD_F32/PK_ADD_{BF16,F16}/CMPSWAP
    // When `hasScaleOffset` is false the multiply is elided by the
    // decoder.
    FlatAddr fa = decodeGlobalStoreAddr(ctx, di, op, /*elemBytes=*/4,
                                         "GLOBAL_ATOMIC");
    Value *addr = fa.ptr;
    // `stData` points to the base of the vdata VGPR range (32-bit for
    // the scalar atomics; CMPSWAP treats it as a 2-vgpr pair
    // cmp/new — see the CMPSWAP branch below).
    Value *data = ctx.regs.readReg32(ctx.B, fa.stData);

    if (sop == SemOp::GLOBAL_ATOMIC_CMPSWAP) {
      // CMPSWAP's vdata is declared as VReg_64 in the .td (a 2-vgpr
      // pair (cmpVal, newVal) in that order).  `fa.stData` is the
      // base of that pair; increment baseIdx to reach newVal.
      Value *cmpVal = data;
      ParsedReg newReg = fa.stData; newReg.baseIdx += 1; newReg.width = 1;
      Value *newVal = ctx.regs.readReg32(ctx.B, newReg);
      ctx.emitUnderExec([&] {
        auto *cas = ctx.B.CreateAtomicCmpXchg(
            addr, cmpVal, newVal, MaybeAlign(), AtomicOrdering::Monotonic,
            AtomicOrdering::Monotonic);
        if (di.numDefs > 0)
          ctx.regs.writeReg32(ctx.B, op.dst(),
                              ctx.B.CreateExtractValue(cas, 0));
      });
      hr.handled = true;
    return hr;
    }

    AtomicRMWInst::BinOp atomicOp;
    Type *atomicTy = ctx.i32Ty;
    bool isFP = false;
    switch (sop) {
    case SemOp::GLOBAL_ATOMIC_ADD:  atomicOp = AtomicRMWInst::Add; break;
    case SemOp::GLOBAL_ATOMIC_SUB:  atomicOp = AtomicRMWInst::Sub; break;
    case SemOp::GLOBAL_ATOMIC_AND:  atomicOp = AtomicRMWInst::And; break;
    case SemOp::GLOBAL_ATOMIC_OR:   atomicOp = AtomicRMWInst::Or; break;
    case SemOp::GLOBAL_ATOMIC_XOR:  atomicOp = AtomicRMWInst::Xor; break;
    case SemOp::GLOBAL_ATOMIC_SMIN: atomicOp = AtomicRMWInst::Min; break;
    case SemOp::GLOBAL_ATOMIC_SMAX: atomicOp = AtomicRMWInst::Max; break;
    case SemOp::GLOBAL_ATOMIC_UMIN: atomicOp = AtomicRMWInst::UMin; break;
    case SemOp::GLOBAL_ATOMIC_UMAX: atomicOp = AtomicRMWInst::UMax; break;
    case SemOp::GLOBAL_ATOMIC_SWAP: atomicOp = AtomicRMWInst::Xchg; break;
    case SemOp::GLOBAL_ATOMIC_ADD_F32:
      atomicOp = AtomicRMWInst::FAdd; atomicTy = ctx.f32Ty; isFP = true; break;
    case SemOp::GLOBAL_ATOMIC_PK_ADD_BF16:
      atomicOp = AtomicRMWInst::FAdd;
      atomicTy = FixedVectorType::get(Type::getBFloatTy(ctx.C), 2); isFP = true; break;
    case SemOp::GLOBAL_ATOMIC_PK_ADD_F16:
      atomicOp = AtomicRMWInst::FAdd;
      atomicTy = FixedVectorType::get(Type::getHalfTy(ctx.C), 2); isFP = true; break;
    default:
      llvm::errs() << "transpiler: Unsupported global atomic variant: " << mn << "\n";
      hr.failure = RaiseFailure::unsupportedShape(
          di, "FLAT", "unsupported global atomic variant");
      return hr;
    }
    if (isFP) data = ctx.B.CreateBitCast(data, atomicTy);
    ctx.emitUnderExec([&] {
      Value *prev = ctx.B.CreateAtomicRMW(atomicOp, addr, data, MaybeAlign(),
                                          AtomicOrdering::Monotonic);
      if (di.numDefs > 0) {
        if (isFP) prev = ctx.B.CreateBitCast(prev, ctx.i32Ty);
        ctx.regs.writeReg32(ctx.B, op.dst(), prev);
      }
    });
    hr.handled = true;
    return hr;
  }
  return hr;
}

} // namespace transpiler
